version: "3"
services:
  database:
    image: postgres:11
    ports:
      - 5432:5432
    env_file: .env
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui